name: Release-plz

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    uses: jwilger/gha-workflows/.github/workflows/rust-release-plz.yml@main
    with:
      runs-on: ubuntu-latest
    secrets:
      op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
