name: Release-plz

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    uses: jwilger/gha-workflows/.github/workflows/rust-release-plz.yml@4f29cb994188c20786a9fda85ebabd113c910d89
    with:
      runs-on: self-hosted-gregor
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      release-signing-key: ${{ secrets.RELEASE_SIGNING_KEY }}
